const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('electronAPI', {
    chatToggleMaximize: () => ipcRenderer.invoke('chat-toggle-maximize'),
onChatMaximized: (cb) => ipcRenderer.on('chat-maximized', (e, s) => cb(s)),
    chatMinimize: () => ipcRenderer.invoke('chat-minimize'),
closeChatWindow: () => ipcRenderer.invoke('close-chat-window'),
chatSendMedia: (payload) => ipcRenderer.send('chat-send-media', payload),
onChatDoSendMedia: (cb) => ipcRenderer.on('chat-do-send-media', (e, p) => cb(p)),
    openChatWindow: () => ipcRenderer.invoke('open-chat-window'),
forwardChat: (msg) => ipcRenderer.send('chat-forward', msg),
pushChatHistory: (msgs) => ipcRenderer.send('chat-history-push', msgs),
requestHistory: () => ipcRenderer.send('chat-request-history'),
chatSend: (text) => ipcRenderer.send('chat-send-from-floating', text),
onChatMessageSync: (cb) => ipcRenderer.on('chat-message-sync', (e, m) => cb(m)),
onChatHistorySync: (cb) => ipcRenderer.on('chat-history-sync', (e, m) => cb(m)),
onChatRequestHistory: (cb) => ipcRenderer.on('chat-request-history', () => cb()),
onChatDoSendText: (cb) => ipcRenderer.on('chat-do-send-text', (e, t) => cb(t)),
onChatWindowClosed: (cb) => ipcRenderer.on('chat-window-closed', () => cb()),
    ensureServer: () => ipcRenderer.invoke('ensure-server'),
    getPersonalPlaylists: () => ipcRenderer.invoke('get-personal-playlists'),
    setPersonalPlaylists: (d) => ipcRenderer.invoke('set-personal-playlists', d),
    winDragStart: () => ipcRenderer.send('win-drag-start'),
    winDragMove: (x, y) => ipcRenderer.send('win-drag-move', x, y),
    winDragEnd: () => ipcRenderer.send('win-drag-end'),
    winMinimize: () => ipcRenderer.invoke('win-minimize'),
    winMaximize: () => ipcRenderer.invoke('win-maximize'),
    winClose: () => ipcRenderer.invoke('win-close'),
    saveMusicFile: (o) => ipcRenderer.invoke('save-music-file', o),
    closeFloatingWindows: (f) => ipcRenderer.invoke('close-floating-windows', f || {}),
    createFloatingWindow: (o) => ipcRenderer.invoke('create-floating-window', o),
    closeFloatingWindow: (id) => ipcRenderer.invoke('close-floating-window', id),
    minimizeFloatingWindow: (id) => ipcRenderer.invoke('minimize-floating-window', id),
    toggleMaximizeFloatingWindow: (id) => ipcRenderer.invoke('toggle-maximize-floating-window', id),
    returnFloatingToMain: (d) => ipcRenderer.invoke('return-floating-to-main', d),
    onRestoreWindowInMain: (cb) => ipcRenderer.on('restore-window-in-main', (e, d) => cb(d)),
    getDeviceSettings: () => ipcRenderer.invoke('get-device-settings'),
    setDeviceSettings: (d) => ipcRenderer.invoke('set-device-settings', d),
    getAutostart: () => ipcRenderer.invoke('get-autostart'),
    setAutostart: (en) => ipcRenderer.invoke('set-autostart', en),
    goStart: (lang) => ipcRenderer.invoke('go-start', lang),
    startServerAndCreate: (nick, lang, offline) => ipcRenderer.invoke('start-server-and-create', nick, lang, offline),
    connectToServer: (info) => ipcRenderer.invoke('connect-to-server', info),
    onServersFound: (cb) => ipcRenderer.on('servers-found', (event, list) => cb(list)),
    selectFolder: () => ipcRenderer.invoke('select-folder'),
    getMusicDir: () => ipcRenderer.invoke('get-music-dir'),
    setMusicDir: (dir) => ipcRenderer.invoke('set-music-dir', dir),
    startMusicShare: () => ipcRenderer.invoke('start-music-share'),
    getLanIp: () => ipcRenderer.invoke('get-lan-ip')
    
});