// ===== ЧАТ, ЭМОДЗИ, МЕДИА =====
const EMOJIS=['😀','😃','😄','😁','😆','😅','🤣','😂','🙂','😉','😊','😇','😍','🤩','😋','😛','😜','🤪','🤑','🤗','🤭','🤔','🤨','😐','😶','😏','😒','🙄','😌','😔','😪','🤤','😷','🤒','🤕','🤢','🤮','🥵','🥶','🥴','😵','🤯','🥳','😎','🤓','😕','😟','🙁','😯','😲','😳','🥺','😦','😧','😨','😰','😥','😢','😭','😱','😖','😣','😞','😓','😩','😫','🥱','😤','😡','😠','👍','👏','👐','🤝','✌️','🤟','🤘','👌','👈','👉','👆','👇','☝️','✋','🤚','🖖','🤙','❤️','💛','💚','💙','💜','🖤','🤍','🤎','💔','❣️','💕','💞','💓','💗','💖','💘','💝','💯','💢','💥','💫','💦','💨','💣','💬','💭','💤','🔥','⭐','🌟','✨','⚡','🎉','🎊','🎈','🎁','🎂','🍰','🎵','🎤','🎸','🎺','🥁','🎮','🎯','🏆','🥇','🥉','🏀','🏈','⚾','🎾','🏐','🏓','🥊','🚕','🚌','🚓','🚑','🚒','✈️','☀️','🌙','☁️','⛄','🌊','🌸','🌻','🌹','🌱','🌴','🐱','🐭','🐹','🐰','🐻','🐨','🐯','🦁','🐷','🐵','🐔','🐧','🐦','🦄','🐝','🦋','🍏','🍎','🍐','🍊','🍋','🍌','🍉','🍇','🍓','🍒','🍑','🍍','🥝','🍅','🥑','🍟','🌭','🍿','🍪','☕','🍺'];
let chatOpen=false,chatFullscreen=false,chatUnreadCount=0,chatMessages=[],emojiPickerOpen=false,mediaMenuOpen=false,pendingMedia=null;
let chatWindowState={x:0,y:0,w:360,h:500};
function initEmojiPicker(){const picker=document.getElementById('emoji-picker');picker.innerHTML='';EMOJIS.forEach(e=>{const btn=document.createElement('button');btn.className='emoji-btn';btn.textContent=e;btn.type='button';btn.onclick=()=>insertEmoji(e);picker.appendChild(btn);});}
function insertEmoji(emoji){const input=document.getElementById('chat-input');const start=input.selectionStart;const end=input.selectionEnd;const text=input.value;input.value=text.substring(0,start)+emoji+text.substring(end);input.selectionStart=input.selectionEnd=start+emoji.length;input.focus();}
function toggleEmojiPicker(){emojiPickerOpen=!emojiPickerOpen;document.getElementById('emoji-picker').classList.toggle('open',emojiPickerOpen);if(emojiPickerOpen){document.getElementById('chat-media-menu').classList.remove('open');mediaMenuOpen=false;}}
function toggleMediaMenu(){mediaMenuOpen=!mediaMenuOpen;document.getElementById('chat-media-menu').classList.toggle('open',mediaMenuOpen);if(mediaMenuOpen){document.getElementById('emoji-picker').classList.remove('open');emojiPickerOpen=false;}}
function pickMedia(type){document.getElementById('chat-media-menu').classList.remove('open');mediaMenuOpen=false;const input=document.getElementById('media-input-'+type);if(input)input.click();}
function handleMediaPicked(event,type){const file=event.target.files[0];if(!file)return;event.target.value='';pendingMedia={type:type,file:file,name:file.name,size:file.size,mimeType:file.type};showMediaPreview();}
function showMediaPreview(){const preview=document.getElementById('chat-media-preview');const content=document.getElementById('media-preview-content');const nameEl=document.getElementById('media-preview-name');const sizeEl=document.getElementById('media-preview-size');content.innerHTML='';if(pendingMedia.type==='image'){const img=document.createElement('img');img.src=URL.createObjectURL(pendingMedia.file);content.appendChild(img);}else if(pendingMedia.type==='video'){const video=document.createElement('video');video.src=URL.createObjectURL(pendingMedia.file);video.muted=true;content.appendChild(video);}else if(pendingMedia.type==='audio'){const audioDiv=document.createElement('div');audioDiv.innerHTML='🎵';audioDiv.style.cssText='width:60px;height:60px;display:flex;align-items:center;justify-content:center;background:#333;border-radius:6px;font-size:24px;';content.appendChild(audioDiv);}else{const fileDiv=document.createElement('div');fileDiv.innerHTML='📄';fileDiv.style.cssText='width:60px;height:60px;display:flex;align-items:center;justify-content:center;background:#333;border-radius:6px;font-size:24px;';content.appendChild(fileDiv);}nameEl.textContent=pendingMedia.name;sizeEl.textContent=formatFileSize(pendingMedia.size);preview.classList.add('active');}
function removeMediaPreview(){pendingMedia=null;document.getElementById('chat-media-preview').classList.remove('active');document.getElementById('chat-upload-progress').style.display='none';}
function toggleChat(){chatOpen=!chatOpen;const win=document.getElementById('chat-window');const fab=document.getElementById('chat-fab');win.style.display=chatOpen?'flex':'none';if(chatOpen){chatUnreadCount=0;updateChatBadge();const msgBox=document.getElementById('chat-messages');msgBox.scrollTop=msgBox.scrollHeight;document.getElementById('chat-input').focus();if(chatFullscreen)fab.classList.add('hidden');}else{emojiPickerOpen=false;document.getElementById('emoji-picker').classList.remove('open');mediaMenuOpen=false;document.getElementById('chat-media-menu').classList.remove('open');fab.classList.remove('hidden');}}
function toggleChatFullscreen(){chatFullscreen=!chatFullscreen;const win=document.getElementById('chat-window');const btn=document.getElementById('chat-fullscreen-btn');const fab=document.getElementById('chat-fab');win.classList.toggle('fullscreen',chatFullscreen);btn.textContent=chatFullscreen?'🗗':'⛶';btn.title=chatFullscreen?'Оконный режим':'Полный экран';if(chatFullscreen){win.style.left='';win.style.top='';win.style.right='';win.style.bottom='';win.style.width='';win.style.height='';fab.classList.add('hidden');updateMediaUsersList();}else{win.style.right='340px';win.style.top='80px';win.style.bottom='auto';win.style.width=chatWindowState.w+'px';win.style.height=chatWindowState.h+'px';fab.classList.remove('hidden');}}
function updateChatBadge(){const badge=document.getElementById('chat-fab-badge');if(chatUnreadCount>0&&!chatOpen){badge.textContent=chatUnreadCount>99?'99+':chatUnreadCount;badge.style.display='block';}else{badge.style.display='none';}}
function renderChatMessage(msg){const box=document.getElementById('chat-messages');const div=document.createElement('div');if(msg.system){div.className='chat-msg system';div.textContent=msg.text;}else{const isSelf=msg.userId===mySocketId;div.className='chat-msg'+(isSelf?' self':'');const header=document.createElement('div');header.className='chat-msg-header';const nameSpan=document.createElement('span');let nameClass='chat-msg-name';let prefix='';if(msg.isAdmin){nameClass+=' admin';prefix='👑 ';}else if(msg.isMod){nameClass+=' mod';prefix='🛡️ ';}else if(msg.isVip){nameClass+=' vip';prefix='⭐ ';}nameSpan.className=nameClass;nameSpan.textContent=prefix+msg.userName;header.appendChild(nameSpan);const timeSpan=document.createElement('span');timeSpan.className='chat-msg-time';const d=new Date(msg.timestamp);timeSpan.textContent=d.getHours().toString().padStart(2,'0')+':'+d.getMinutes().toString().padStart(2,'0');header.appendChild(timeSpan);div.appendChild(header);if(msg.text){const textDiv=document.createElement('div');textDiv.className='chat-msg-text';textDiv.textContent=msg.text;div.appendChild(textDiv);}if(msg.mediaType&&msg.fileUrl){const mediaDiv=document.createElement('div');mediaDiv.className='chat-msg-media';if(msg.mediaType==='image'){const img=document.createElement('img');img.src=msg.fileUrl;img.loading='lazy';img.onclick=()=>openMediaViewer(msg.fileUrl,'image',msg.fileName);mediaDiv.appendChild(img);}else if(msg.mediaType==='video'){const video=document.createElement('video');video.src=msg.fileUrl;video.controls=true;video.preload='metadata';if(selectedSpeakerId&&video.setSinkId)video.setSinkId(selectedSpeakerId).catch(()=>{});mediaDiv.appendChild(video);}else if(msg.mediaType==='audio'){const audioEl=document.createElement('audio');audioEl.src=msg.fileUrl;audioEl.controls=true;audioEl.preload='metadata';if(selectedSpeakerId&&audioEl.setSinkId)audioEl.setSinkId(selectedSpeakerId).catch(()=>{});mediaDiv.appendChild(audioEl);}else{const link=document.createElement('a');link.href=msg.fileUrl;link.download=msg.fileName||'file';link.innerHTML='📄 '+escapeHtml(msg.fileName||'Скачать файл')+' ('+formatFileSize(msg.fileSize||0)+')';mediaDiv.appendChild(link);}div.appendChild(mediaDiv);}}box.appendChild(div);box.scrollTop=box.scrollHeight;}
function openMediaViewer(url,type,fileName){const viewer=document.getElementById('media-viewer');const content=document.getElementById('media-viewer-content');const downloadBtn=document.getElementById('media-viewer-download');content.innerHTML='';if(type==='image'){const img=document.createElement('img');img.src=url;content.appendChild(img);}else{const video=document.createElement('video');video.src=url;video.controls=true;video.autoplay=true;content.appendChild(video);if(selectedSpeakerId&&video.setSinkId)video.setSinkId(selectedSpeakerId).catch(()=>{});}downloadBtn.href=url;downloadBtn.download=fileName||(type==='image'?'image.png':'video.mp4');viewer.classList.add('open');}
function closeMediaViewer(){const viewer=document.getElementById('media-viewer');const content=document.getElementById('media-viewer-content');const video=content.querySelector('video');if(video){video.pause();video.src='';}content.innerHTML='';viewer.classList.remove('open');}
async function sendChatMessage(){const input=document.getElementById('chat-input');const text=input.value.trim();if(!text&&!pendingMedia)return;if(pendingMedia){const progress=document.getElementById('chat-upload-progress');const progressBar=document.getElementById('chat-upload-progress-bar');progress.style.display='block';progressBar.style.width='10%';const formData=new FormData();formData.append('file',pendingMedia.file);try{const response=await fetch('/api/upload-chat',{method:'POST',body:formData});progressBar.style.width='80%';const result=await response.json();if(result.success){progressBar.style.width='100%';socket.emit('send-chat-media',{type:result.type,fileUrl:result.url,fileName:result.name,fileSize:result.size,text:text});setTimeout(()=>{progress.style.display='none';progressBar.style.width='0';},300);}else{showToast(result.error||'Ошибка загрузки',true);progress.style.display='none';progressBar.style.width='0';}}catch(e){showToast('Ошибка загрузки файла',true);progress.style.display='none';progressBar.style.width='0';}removeMediaPreview();}else{socket.emit('send-chat-message',text);}input.value='';input.style.height='auto';}
socket.on('chat-error',msg=>{showToast(msg||'Ошибка отправки',true);});
socket.on('chat-message',msg=>{chatMessages.push(msg);renderChatMessage(msg);if(!chatOpen||document.hidden){chatUnreadCount++;updateChatBadge();}});
socket.on('chat-history',messages=>{chatMessages=messages||[];const box=document.getElementById('chat-messages');box.innerHTML='';chatMessages.forEach(m=>renderChatMessage(m));});
document.getElementById('chat-input').addEventListener('input',function(){this.style.height='auto';this.style.height=Math.min(this.scrollHeight,80)+'px';});
document.getElementById('chat-input').addEventListener('keydown',function(e){if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();sendChatMessage();}});
document.addEventListener('click',function(e){const picker=document.getElementById('emoji-picker');const emojiBtn=document.querySelector('.chat-emoji-btn');const mediaMenu=document.getElementById('chat-media-menu');const mediaBtn=document.querySelector('.chat-media-btn');if(emojiPickerOpen&&!picker.contains(e.target)&&!emojiBtn.contains(e.target)){emojiPickerOpen=false;picker.classList.remove('open');}if(mediaMenuOpen&&!mediaMenu.contains(e.target)&&!mediaBtn.contains(e.target)){mediaMenuOpen=false;mediaMenu.classList.remove('open');}});
document.addEventListener('keydown',function(e){if(e.key==='Escape'){const viewer=document.getElementById('media-viewer');if(viewer.classList.contains('open')){closeMediaViewer();}}});
(function(){const header=document.getElementById('chat-header');const win=document.getElementById('chat-window');let isDragging=false,offsetX=0,offsetY=0;header.addEventListener('mousedown',function(e){if(chatFullscreen)return;if(e.target.closest('.chat-btn'))return;isDragging=true;const rect=win.getBoundingClientRect();offsetX=e.clientX-rect.left;offsetY=e.clientY-rect.top;win.style.right='auto';win.style.bottom='auto';win.style.left=rect.left+'px';win.style.top=rect.top+'px';e.preventDefault();});document.addEventListener('mousemove',function(e){if(!isDragging)return;let x=e.clientX-offsetX;let y=e.clientY-offsetY;x=Math.max(0,Math.min(window.innerWidth-win.offsetWidth,x));y=Math.max(0,Math.min(window.innerHeight-win.offsetHeight,y));win.style.left=x+'px';win.style.top=y+'px';});document.addEventListener('mouseup',function(){isDragging=false;});})();
(function(){const resizer=document.getElementById('chat-resize');const win=document.getElementById('chat-window');let isResizing=false,startX,startY,startW,startH,startLeft,startTop;resizer.addEventListener('mousedown',function(e){if(chatFullscreen)return;isResizing=true;startX=e.clientX;startY=e.clientY;startW=win.offsetWidth;startH=win.offsetHeight;const rect=win.getBoundingClientRect();startLeft=rect.left;startTop=rect.top;win.style.left=startLeft+'px';win.style.top=startTop+'px';win.style.right='auto';win.style.bottom='auto';e.preventDefault();});document.addEventListener('mousemove',function(e){if(!isResizing)return;const dx=e.clientX-startX;const dy=e.clientY-startY;const newW=Math.max(280,Math.min(window.innerWidth-startLeft-20,startW+dx));const newH=Math.max(300,Math.min(window.innerHeight-startTop-20,startH+dy));win.style.width=newW+'px';win.style.height=newH+'px';chatWindowState.w=newW;chatWindowState.h=newH;});document.addEventListener('mouseup',function(){isResizing=false;});})();
window.addEventListener('focus',function(){if(chatOpen){chatUnreadCount=0;updateChatBadge();}});