// ===== СПРАВКА: отдельный файл, работает на старте и в комнате =====
function guideImgSrc(p){return window.location.protocol==='file:'?p:('/'+p);}
const GUIDE_SECTIONS=[
{img:'guide/01-start.png',t:{ru:'1. Стартовый экран',en:'1. Start screen'},p:{ru:'Никнейм — твоё имя в комнате.\n«Создать комнату» — создаёт комнату, ты становишься админом. Если интернета нет, предложится создать локальную комнату (см. п.16).\n«Войти» — вход по 5-значному коду.\n«Комнаты в локальной сети» — список комнат, открытых в твоей сети (клик — войти).\n«Прямое подключение» — введи IP:код или IP:порт чужого сервера; галочка HTTPS — подключение по https.\n⚙ справа сверху — настройки.',en:'Nickname — your name in rooms.\n"Create room" — creates a room, you become admin. With no internet it offers a local room (see §16).\n"Join" — enter by 5-digit code.\n"Rooms in local network" — list of LAN-open rooms (click to join).\n"Direct connect" — type IP:code or IP:port of another server; HTTPS checkbox — connect via https.\n⚙ top-right — settings.'}},
{img:'guide/02-settings.png',t:{ru:'2. Настройки (⚙)',en:'2. Settings (⚙)'},p:{ru:'Микрофон / Динамики / Камера — устройства ввода-вывода (динамики применяются и к музыке, и к войсу).\n«Настройки музыки» — папка с треками, «Личные плейлисты» (📚) и «Моя музыка» (📝): доступны и здесь, и в комнате.\n«Запуск при включении компьютера» — автозапуск с Windows (по умолчанию выкл).\nЯзык переключается кнопками RU/EN на старте и в комнате.',en:'Mic / Speakers / Camera — input-output devices (speakers apply to music and voice).\n"Music settings" — track folder, "Personal playlists" (📚) and "My music" (📝): available here and in the room.\n"Launch at system startup" — autostart with Windows (off by default).\nLanguage switches with RU/EN on start and in the room.'}},
{img:'guide/03-sidebar.png',t:{ru:'3. Комната: левая панель',en:'3. Room: left panel'},p:{ru:'Код комнаты — клик копирует в буфер.\n🔄 — новый код (админ), 🚪 — выход (у админа выход закрывает комнату).\n⚡ Технические настройки: видимость в LAN, включение войс-чата; у админа также ⚡ Настройки голосования (кулдаун и время голосования).\n👥 — режим управления: выдача VIP/MOD, ❌ кик, 🚫 бан.\n«Войти в войс чат» / «Выйти» — голосовая связь; у участников в войсе появляются ползунки громкости (громкость каждого запоминается).',en:'Room code — click to copy.\n🔄 — new code (admin), 🚪 — leave (admin leaving closes the room).\n⚡ Technical settings: LAN visibility, voice chat toggle; admin also has ⚡ Voting settings (cooldown and duration).\n👥 — manage mode: grant VIP/MOD, ❌ kick, 🚫 ban.\n"Join voice chat" / "Leave" — voice; voice peers get volume sliders (each volume is remembered).'}},
{img:'guide/04-search.png',t:{ru:'4. Поиск, режимы и фильтры',en:'4. Search, views & filters'},p:{ru:'Поле поиска: обычный запрос — Deezer + твои треки; #full или #скачанное — только треки активного плейлиста. История запросов — клик по полю.\n⚙ справа от поиска — «Настройки песен»: режим «Страницы по 5» или «Списком» (скролл по всему результату), сортировка по Названию/Автору (повторный клик — обратный порядок), фильтр по типу (Все / Local / URL) и по игроку. При долгой подгрузке крутится кольцо загрузки.\n➕ — меню «Добавить файлом» / «Добавить ссылкой».\n📚 — «Личные плейлисты», 📝 — «Моя музыка» (двойной клик по треку — редактирование, доступно и на старте).',en:'Search field: plain query — Deezer + your tracks; #full or #downloaded — only active playlist tracks. Click the field for history.\n⚙ right of search — "Song settings": view "Pages of 5" or "List" (scroll through the whole result), sort by Title/Artist (click again — reverse), filter by type (All / Local / URL) and by player. A spinner shows on slow loads.\n➕ — menu "Add from file" / "Add by URL".\n📚 — "Personal playlists", 📝 — "My music" (double-click a track — edit, available on start too).'}},
{img:'guide/05-results.png',t:{ru:'5. Карточки поиска',en:'5. Search cards'},p:{ru:'▶ — играть сейчас (админ/MOD).\nКнопка очереди — добавить в очередь (админ/MOD/VIP).\n🗳 — голосование админа; 📩 — предложить трек админу (гость, с кулдауном).\nЗначки 💾 Local (Full) / 🔗 URL — трек из локальной библиотеки или URL-трек.',en:'▶ — play now (admin/MOD).\nQueue button — add to queue (admin/MOD/VIP).\n🗳 — admin poll; 📩 — suggest a track to admin (guest, with cooldown).\nBadges 💾 Local (Full) / 🔗 URL — local library track or URL track.'}},
{img:'guide/06-add.png',t:{ru:'6. Добавление треков',en:'6. Adding tracks'},p:{ru:'Ссылкой: прямые mp3/wav/ogg, deezer.com/track/…, archive.org/details/…; обложка авто или своя через 📷. Мёртвая ссылка автоматически скипается, чтобы очередь не вставала.\nФайлом: mp3/wav/ogg/flac/m4a; название/исполнитель/альбом и обложка читаются из тегов файла, всё можно поправить; файл копируется в твою папку музыки.\nНовый трек по умолчанию ВЫКЛЮЧЕН в плейлистах — включи галочкой в настройках плейлиста. В офлайн-комнате url-треки недоступны.',en:'By URL: direct mp3/wav/ogg, deezer.com/track/…, archive.org/details/…; cover auto or yours via 📷. A dead link auto-skips so the queue never stalls.\nBy file: mp3/wav/ogg/flac/m4a; title/artist/album and cover are read from file tags, all editable; the file is copied to your music folder.\nA new track is OFF in playlists by default — enable it with a checkbox in playlist settings. URL tracks are unavailable in an offline room.'}},
{img:'guide/07-edit.png',t:{ru:'7. Редактирование треков (📝)',en:'7. Editing tracks (📝)'},p:{ru:'Двойной клик по треку (в «Моя музыка» на старте или в комнате): название, исполнитель, альбом, ссылка (для URL), обложка 📷 и галочка «авто-обложка по названию».\nСнял галочку без выбора фото — вернётся прежняя обложка (включая встроенную в файл).\nИзменения видны всем в комнате сразу.',en:'Double-click a track (in "My music" on start or in the room): title, artist, album, link (for URL), cover 📷 and "auto-cover by title" checkbox.\nUnchecking without picking a photo restores the previous cover (including the one embedded in the file).\nChanges are visible to everyone in the room immediately.'}},
{img:'guide/08-playlist.png',t:{ru:'8. Плейлисты комнаты и галочки',en:'8. Room playlists & checks'},p:{ru:'Панель плейлиста справа: ←→ — листать, + — новый, ⚙ — настройки, клик по названию — активный плейлист (админ) или просмотр состава (гость/VIP).\nВ ⚙: галочка у ника = «у участника есть включённые треки»; клик по ней включает/выключает ВСЕ его треки (включая url), и она сама гаснет, если выключить все его треки вручную. Клик по нику (не по галочке) открывает его личные плейлисты/треки с галочками. Галочка личного плейлиста = «из него есть включённые треки»; клик включает/выключает весь плейлист. Одна и та же песня в нескольких плейлистах учитывается один раз.\n«📤 Запросить треки» — шаринг музыки участника. Новые треки появляются без галочки.',en:'Playlist panel on the right: ←→ browse, + new, ⚙ settings, click the name — set active (admin) or view content (guest/VIP).\nIn ⚙: the nick checkbox = "the member has enabled tracks"; clicking it toggles ALL his tracks (incl. url), and it clears itself when you disable all his tracks by hand. Clicking the nick (not the box) opens his personal playlists/tracks with checkboxes. A personal-playlist checkbox = "some of its tracks are enabled"; clicking toggles the whole playlist. The same song in several playlists counts once.\n"📤 Request tracks" — member music sharing. Newly added tracks appear unchecked.'}},
{t:{ru:'9. Личные плейлисты (📚)',en:'9. Personal playlists (📚)'},p:{ru:'Открываются на старте (⚙ → Настройки музыки → 📚) и в комнате (⚙ настроек песен → 📚, или кнопка 📚 в панели).\nМенеджер: «+» — новый плейлист, двойной клик по плейлисту — редактор.\nРедактор: слева «Все треки» (вся твоя музыка: локальные + url), справа «В плейлисте»; галочкой переносишь треки, поиск по каждой колонке, «Удалить»/«Сохранить».\nГалочка «Авто-добавление в комнату (📤)» — плейлист сам передаётся в комнату при входе. Без неё передача идёт по запросу админа («📤 Запросить треки»), где ты отмечаешь, какие плейлисты отдать.',en:'Open on start (⚙ → Music settings → 📚) and in the room (song-settings ⚙ → 📚, or the 📚 button in the panel).\nManager: "+" — new playlist, double-click a playlist — editor.\nEditor: left "All tracks" (your whole library: local + url), right "In playlist"; toggle tracks across, search in each column, "Delete"/"Save".\n"Auto-add to room (📤)" checkbox — the playlist is shared to the room on join. Without it, sharing happens on admin request ("📤 Request tracks"), where you pick which playlists to give.'}},
{img:'guide/09-queue.png',t:{ru:'10. Очередь и рандом',en:'10. Queue & random'},p:{ru:'Список очереди: ▲▼ — порядок (админ/MOD/VIP), ✕ — убрать (админ/MOD).\nСверху — «Сейчас играет» и «Предыдущая».\n🎲 Режим рандома (админ/MOD): автоматически подмешивает случайные треки плейлиста, не повторяя недавние исполнители.',en:'Queue list: ▲▼ reorder (admin/MOD/VIP), ✕ remove (admin/MOD).\nTop — "Now playing" and "Previous".\n🎲 Random mode (admin/MOD): auto-mixes random playlist tracks, avoiding recent artists.'}},
{img:'guide/10-player.png',t:{ru:'11. Плеер',en:'11. Player'},p:{ru:'⏮ ▶ ⏭ 🔁 — предыдущий, play/pause, следующий, повтор (админ/MOD).\nПолоса прогресса — перемотка (админ/MOD), у гостей только просмотр.\nГромкость справа 0–200% — локальная у каждого. Источник всегда стартует свежий трек с 0; гости догоняют по времени автоматически.',en:'⏮ ▶ ⏭ 🔁 — previous, play/pause, next, repeat (admin/MOD).\nProgress bar — seek (admin/MOD), guests view-only.\nVolume on the right 0–200% — local per user. The source always starts a fresh track at 0; guests catch up automatically.'}},
{img:'guide/11-inbox.png',t:{ru:'12. Запросы админу',en:'12. Admin inbox'},p:{ru:'Панель внизу по центру: ▶ играть сейчас, 🗳 опрос, ⏭ следующим, ⬇ в конец, ❌ отклонить.\nРезультаты опроса видны прямо в панели.',en:'Bottom-center panel: ▶ play now, 🗳 poll, ⏭ next, ⬇ to end, ❌ reject.\nPoll results show right in the panel.'}},
{img:'guide/12-chat.png',t:{ru:'13. Чат',en:'13. Chat'},p:{ru:'💬 справа сверху: сообщения, 😊 эмодзи, 📎 файлы/фото/видео/аудио, ⛶ полноэкранный режим.\nОкно чата можно перетаскивать за шапку и менять размер за правый нижний угол; из полного экрана оно возвращается ровно на то место и с тем размером, где ты его оставил.\nНепрочитанные — счётчик на кнопке. Клик по картинке — просмотр на весь экран.',en:'💬 top-right: messages, 😊 emoji, 📎 files/photos/videos/audio, ⛶ fullscreen.\nThe chat window is draggable by its header and resizable by the bottom-right corner; exiting fullscreen returns it exactly to the place and size you left it.\nUnread — badge on the button. Click an image for fullscreen view.'}},
{img:'guide/13-media.png',t:{ru:'14. Видео и трансляции',en:'14. Video & screen sharing'},p:{ru:'В чате справа: «📷 Видеосвязь» и «📺 Трансляция экрана».\nСписок «Участники с медиа»: «📹 Видео» / «📺 Экран» — открыть плавающее окно просмотра (свою трансляцию включать не нужно).\nОкна можно таскать, ресайзить и разворачивать на весь экран.',en:'In chat on the right: "📷 Video" and "📺 Share screen".\n"Users with media" list: "📹 Video" / "📺 Screen" — open a floating viewer window (you don\'t need to share yours).\nWindows are draggable, resizable and fullscreenable.'}},
{t:{ru:'15. Роли и синхронизация',en:'15. Roles & sync'},p:{ru:'👑 Админ: музыка, очередь, роли, бан, плейлисты, рандом.\n🛡️ MOD: почти как админ, без ролей и бана.\n⭐ VIP: добавление в очередь и шаринг по запросу.\nГость: слушает, голосует, предлагает треки.\nМузыка синхронна у всех; рассинхрон корректируется автоматически, мёртвые url скипаются.',en:'👑 Admin: music, queue, roles, ban, playlists, random.\n🛡️ MOD: almost admin, without roles and ban.\n⭐ VIP: adding to queue and sharing on request.\nGuest: listens, votes, suggests tracks.\nMusic is synced for everyone; drift is corrected automatically, dead urls skip.'}},
{t:{ru:'16. Офлайн-комната',en:'16. Offline room'},p:{ru:'Если при создании комнаты интернета нет, вылезает окно: «Создать локальную комнату» / «Попробовать ещё раз» / ✕ (отмена).\nВ локальной комнате нет 30-секундных превью Deezer, нет обложек из интернета и нет url-песен, и по коду к тебе не подключатся друзья — но локальные файлы из твоей папки и их встроенные обложки работают, очередь и плейлисты тоже.\n«Попробовать ещё раз» повторяет проверку сети, ✕ отменяет создание.',en:'If there is no internet when creating a room, a dialog appears: "Create local room" / "Try again" / ✕ (cancel).\nA local room has no 30s Deezer previews, no internet covers and no url tracks, and friends cannot join by code — but local files from your folder and their embedded covers work, as do queue and playlists.\n"Try again" re-checks the network, ✕ cancels creation.'}}
];
function buildGuideModal(){
const d=document.createElement('div');d.id='guide-modal';
d.innerHTML='<div class="guide-box"><button class="guide-close" onclick="closeGuide()">✕</button><h2 style="margin:0 0 14px;">📖 Справка MusicPulse</h2><div id="guide-content"></div></div>';
return d;
}
function openGuide(){
let m=document.getElementById('guide-modal');if(!m){m=buildGuideModal();document.body.appendChild(m);}
const c=document.getElementById('guide-content');c.innerHTML='';
const lang=(typeof currentLang!=='undefined'&&currentLang==='en')?'en':'ru';
GUIDE_SECTIONS.forEach(s=>{
const h=document.createElement('h3');h.className='guide-h';h.textContent=s.t[lang]||s.t.ru;c.appendChild(h);
if(s.img){const im=document.createElement('img');im.src=guideImgSrc(s.img);im.loading='lazy';im.onerror=function(){this.style.display='none';};c.appendChild(im);}
const p=document.createElement('p');p.className='guide-p';p.textContent=s.p[lang]||s.p.ru;c.appendChild(p);
});
m.classList.add('open');
}
function closeGuide(){const m=document.getElementById('guide-modal');if(m)m.classList.remove('open');}
document.addEventListener('DOMContentLoaded',()=>{
if(!document.getElementById('guide-fab')){
const b=document.createElement('button');b.id='guide-fab';b.className='guide-fab';b.textContent='❓';b.title='Справка / Guide';b.onclick=function(){const m=document.getElementById('guide-modal');if(m&&m.classList.contains('open'))closeGuide();else openGuide();};document.body.appendChild(b);
}
if(!document.getElementById('guide-modal'))document.body.appendChild(buildGuideModal());
if(!document.getElementById('app-dragbar')){
const db=document.createElement('div');db.id='app-dragbar';
db.innerHTML='<span class="db-title">🎵 MusicPulse</span><span class="db-spacer"></span><button class="db-btn" id="db-min" title="Свернуть">—</button><button class="db-btn" id="db-max" title="Развернуть/свернуть окно">⛶</button><button class="db-btn db-close" id="db-close" title="Закрыть">✕</button>';
document.body.appendChild(db);
document.getElementById('db-min').onclick=()=>{if(window.electronAPI&&window.electronAPI.winMinimize)window.electronAPI.winMinimize();};
document.getElementById('db-max').onclick=()=>{if(window.electronAPI&&window.electronAPI.winMaximize)window.electronAPI.winMaximize();};
document.getElementById('db-close').onclick=()=>{if(window.electronAPI&&window.electronAPI.winClose)window.electronAPI.winClose();};
db.addEventListener('mousedown',e=>{
if(e.target.closest('.db-btn'))return;
if(!(window.electronAPI&&window.electronAPI.winDragStart))return;
window.electronAPI.winDragStart();
const mm=ev=>window.electronAPI.winDragMove(ev.screenX,ev.screenY);
const mu=()=>{window.electronAPI.winDragEnd();window.removeEventListener('mousemove',mm);window.removeEventListener('mouseup',mu);};
window.addEventListener('mousemove',mm);
window.addEventListener('mouseup',mu);
e.preventDefault();
});
db.addEventListener('dblclick',e=>{if(!e.target.closest('.db-btn')&&window.electronAPI&&window.electronAPI.winMaximize)window.electronAPI.winMaximize();});
}
const st=document.createElement('style');
st.textContent='.guide-fab{position:fixed;left:12px;bottom:12px;width:44px;height:44px;border-radius:50%;border:1px solid #3a3a3a;background:#1e1e1e;color:#b3b3b3;font-size:20px;cursor:pointer;z-index:3200;box-shadow:0 4px 12px rgba(0,0,0,.45);}.guide-fab:hover{color:#1db954;border-color:#1db954;}#guide-modal{position:fixed;inset:0;background:rgba(0,0,0,.78);display:none;align-items:center;justify-content:center;z-index:3100;}#guide-modal.open{display:flex;}#guide-modal .guide-box{width:720px;max-width:94vw;max-height:86vh;background:#1e1e1e;border:1px solid #3a3a3a;border-radius:14px;padding:22px;display:flex;flex-direction:column;position:relative;box-shadow:0 12px 40px rgba(0,0,0,.6);}#guide-content{overflow-y:auto;padding-right:8px;}.guide-close{position:absolute;top:12px;right:14px;background:none;border:none;color:#888;font-size:16px;cursor:pointer;padding:4px;line-height:1;z-index:2;}.guide-close:hover{color:#fff;}#guide-content .guide-h{font-size:14px;color:#1db954;margin:14px 0 6px;}#guide-content .guide-h:first-child{margin-top:0;}#guide-content .guide-p{font-size:13px;color:#ddd;line-height:1.55;margin:0 0 8px;white-space:pre-wrap;}#guide-content img{max-width:100%;border-radius:8px;border:1px solid #333;margin:4px 0 10px;display:block;}#app-dragbar{position:fixed;top:0;left:0;right:0;height:34px;background:#121212;border-bottom:1px solid #262626;z-index:9998;display:flex;align-items:center;padding:0 4px 0 8px;user-select:none;}#app-dragbar .db-title{font-size:12px;color:#8a8a8a;font-weight:600;}#app-dragbar .db-spacer{flex:1;}#app-dragbar .db-btn{-webkit-app-region:no-drag;background:none;border:none;color:#9a9a9a;font-size:12px;line-height:1;height:34px;padding:0 12px;cursor:pointer;}#app-dragbar .db-btn:hover{background:#2a2a2a;color:#fff;}#app-dragbar .db-close:hover{background:#e74c3c;color:#fff;}';
document.head.appendChild(st);
});