// ===== СПРАВКА: отдельный файл, работает на старте и в комнате =====
function guideImgSrc(p){return window.location.protocol==='file:'?p:('/'+p);}
const GUIDE_SECTIONS=[
{img:'guide/01-start.png',t:{ru:'1. Стартовый экран',en:'1. Start screen'},p:{ru:'Никнейм — твоё имя в комнате.\n«Создать комнату» — создаёт комнату, ты становишься админом.\n«Войти» — вход по 5-значному коду.\n«Комнаты в локальной сети» — список комнат, открытых в твоей сети (клик — войти).\n«Прямое подключение» — введи IP:код или IP:порт чужого сервера; галочка HTTPS — подключение по https.\n⚙ справа сверху — настройки.',en:'Nickname — your name in rooms.\n"Create room" — creates a room, you become admin.\n"Join" — enter by 5-digit code.\n"Rooms in local network" — list of LAN-open rooms (click to join).\n"Direct connect" — type IP:code or IP:port of another server; HTTPS checkbox — connect via https.\n⚙ top-right — settings.'}},
{img:'guide/02-settings.png',t:{ru:'2. Настройки (⚙)',en:'2. Settings (⚙)'},p:{ru:'Микрофон / Динамики / Камера — устройства ввода-вывода (динамики применяются и к музыке, и к войсу).\n«Папка с музыкой» — откуда берутся твои скачанные треки.\n«Запуск при включении компьютера» — автозапуск с Windows (по умолчанию выкл).\nЯзык переключается на старте кнопками RU/EN.',en:'Mic / Speakers / Camera — input-output devices (speakers apply to music and voice).\n"Music folder" — where your downloaded tracks come from.\n"Launch at system startup" — autostart with Windows (off by default).\nLanguage switches with RU/EN buttons on the start screen.'}},
{img:'guide/03-sidebar.png',t:{ru:'3. Комната: левая панель',en:'3. Room: left panel'},p:{ru:'Код комнаты — клик копирует в буфер.\n🔄 — новый код (админ), 🚪 — выход (у админа выход закрывает комнату).\n⚡ Технические настройки: видимость в LAN, включение войс-чата; у админа также ⚡ Настройки голосования (кулдаун и время голосования).\n👥 — режим управления: выдача VIP/MOD, ❌ кик, 🚫 бан.\n«Войти в войс чат» / «Выйти» — голосовая связь; у участников в войсе появляются ползунки громкости (громкость каждого запоминается).',en:'Room code — click to copy.\n🔄 — new code (admin), 🚪 — leave (admin leaving closes the room).\n⚡ Technical settings: LAN visibility, voice chat toggle; admin also has ⚡ Voting settings (cooldown and duration).\n👥 — manage mode: grant VIP/MOD, ❌ kick, 🚫 ban.\n"Join voice chat" / "Leave" — voice; voice peers get volume sliders (each volume is remembered).'}},
{img:'guide/04-search.png',t:{ru:'4. Поиск и добавление',en:'4. Search & adding'},p:{ru:'Поле поиска: обычный запрос — Deezer + твои треки; #full или #скачанное — только треки активного плейлиста. История запросов открывается кликом по полю.\n➕ — меню «Добавить файлом» / «Добавить ссылкой».\n📝 — «Моя музыка»: список твоих треков, поиск, 🗑 удаление, двойной клик — редактирование.\n❓ слева внизу — эта справка.',en:'Search field: plain query — Deezer + your tracks; #full or #downloaded — only active playlist tracks. Click the field for history.\n➕ — menu "Add from file" / "Add by URL".\n📝 — "My music": your tracks, search, 🗑 delete, double-click — edit.\n❓ bottom-left — this guide.'}},
{img:'guide/05-results.png',t:{ru:'5. Карточки поиска',en:'5. Search cards'},p:{ru:'▶ — играть сейчас (админ/MOD).\nКнопка очереди — добавить в очередь (админ/MOD/VIP).\n🗳 — голосование админа; 📩 — предложить трек админу (гость, с кулдауном).\nЗначки 💾 Full / 🔗 Full url — трек из локальной библиотеки или URL-трек.',en:'▶ — play now (admin/MOD).\nQueue button — add to queue (admin/MOD/VIP).\n🗳 — admin poll; 📩 — suggest a track to admin (guest, with cooldown).\nBadges 💾 Full / 🔗 Full url — local library track or URL track.'}},
{img:'guide/06-add.png',t:{ru:'6. Добавление треков',en:'6. Adding tracks'},p:{ru:'Ссылкой: поддерживаются прямые mp3/wav/ogg, deezer.com/track/…, archive.org/details/…; обложка авто или своя через 📷.\nФайлом: mp3/wav/ogg/flac/m4a; название/исполнитель/альбом и обложка читаются из тегов файла, всё можно поправить; файл копируется в твою папку музыки.\nНовый трек по умолчанию ВЫКЛЮЧЕН в плейлистах — включи галочкой в настройках плейлиста.',en:'By URL: direct mp3/wav/ogg, deezer.com/track/…, archive.org/details/… are supported; cover auto or yours via 📷.\nBy file: mp3/wav/ogg/flac/m4a; title/artist/album and cover are read from file tags, all editable; the file is copied to your music folder.\nA new track is OFF in playlists by default — enable it with a checkbox in playlist settings.'}},
{img:'guide/07-edit.png',t:{ru:'7. Редактирование треков (📝)',en:'7. Editing tracks (📝)'},p:{ru:'Двойной клик по треку: название, исполнитель, альбом, ссылка (для URL), обложка 📷 и галочка «авто-обложка по названию».\nСнял галочку без выбора фото — вернётся прежняя обложка (включая встроенную в файл).\nИзменения видны всем в комнате сразу.',en:'Double-click a track: title, artist, album, link (for URL), cover 📷 and "auto-cover by title" checkbox.\nUnchecking without picking a photo restores the previous cover (including the one embedded in the file).\nChanges are visible to everyone in the room immediately.'}},
{img:'guide/08-playlist.png',t:{ru:'8. Плейлисты',en:'8. Playlists'},p:{ru:'Панель плейлиста справа: ←→ — листать, + — новый, ⚙ — настройки, клик по названию — активный плейлист (админ) или просмотр состава (гость/VIP).\nВ ⚙: галочка участника = все его треки; двойной клик по участнику = список его треков с галочками; «📤 Запросить треки» — шаринг музыки участника.\nНовые добавленные треки появляются в списке без галочки.',en:'Playlist panel on the right: ←→ browse, + new, ⚙ settings, click the name — set active (admin) or view content (guest/VIP).\nIn ⚙: member checkbox = all his tracks; double-click a member = his track list with checkboxes; "📤 Request tracks" — member music sharing.\nNewly added tracks appear unchecked.'}},
{img:'guide/09-queue.png',t:{ru:'9. Очередь и рандом',en:'9. Queue & random'},p:{ru:'Список очереди: ▲▼ — порядок (админ/MOD/VIP), ✕ — убрать (админ/MOD).\nСверху — «Сейчас играет» и «Предыдущая».\n🎲 Режим рандома (админ/MOD): автоматически подмешивает случайные треки плейлиста.',en:'Queue list: ▲▼ reorder (admin/MOD/VIP), ✕ remove (admin/MOD).\nTop — "Now playing" and "Previous".\n🎲 Random mode (admin/MOD): automatically mixes in random playlist tracks.'}},
{img:'guide/10-player.png',t:{ru:'10. Плеер',en:'10. Player'},p:{ru:'⏮ ▶ ⏭ 🔁 — предыдущий, play/pause, следующий, повтор (админ/MOD).\nПолоса прогресса — перемотка (админ/MOD), у гостей только просмотр.\nГромкость справа 0–200% — локальная у каждого.',en:'⏮ ▶ ⏭ 🔁 — previous, play/pause, next, repeat (admin/MOD).\nProgress bar — seek (admin/MOD), guests view-only.\nVolume on the right 0–200% — local for each user.'}},
{img:'guide/11-inbox.png',t:{ru:'11. Запросы админу',en:'11. Admin inbox'},p:{ru:'Панель внизу по центру: ▶ играть сейчас, 🗳 опрос, ⏭ следующим, ⏬ в конец, ❌ отклонить.\nРезультаты опроса видны прямо в панели.',en:'Bottom-center panel: ▶ play now, 🗳 poll, ⏭ next,  to end,  reject.\nPoll results show right in the panel.'}},
{img:'guide/12-chat.png',t:{ru:'12. Чат',en:'12. Chat'},p:{ru:'💬 справа сверху: сообщения, 😊 эмодзи, 📎 файлы/фото/видео/аудио, ⛶ полноэкранный режим.\nНепрочитанные — счётчик на кнопке. Клик по картинке — просмотр на весь экран.',en:'💬 top-right: messages, 😊 emoji,  files/photos/videos/audio, ⛶ fullscreen.\nUnread — badge on the button. Click an image for fullscreen view.'}},
{img:'guide/13-media.png',t:{ru:'13. Видео и трансляции',en:'13. Video & screen sharing'},p:{ru:'В чате справа: «📷 Видеосвязь» и «📺 Трансляция экрана».\nСписок «Участники с медиа»: «📹 Видео» / «📺 Экран» — открыть плавающее окно просмотра (свою трансляцию включать не нужно).\nОкна можно таскать, ресайзить и разворачивать на весь экран.',en:'In chat on the right: "📷 Video" and "📺 Share screen".\n"Users with media" list: "📹 Video" / "📺 Screen" — open a floating viewer window (you don\u2019t need to share yours).\nWindows are draggable, resizable and fullscreenable.'}},
{t:{ru:'14. Роли и синхронизация',en:'14. Roles & sync'},p:{ru:'👑 Админ: музыка, очередь, роли, бан, плейлисты, рандом.\n🛡️ MOD: почти как админ, без ролей и бана.\n⭐ VIP: добавление в очередь и шаринг по запросу.\nГость: слушает, голосует, предлагает треки.\nМузыка синхронна у всех; рассинхрон корректируется автоматически.',en:'👑 Admin: music, queue, roles, ban, playlists, random.\n🛡️ MOD: almost admin, without roles and ban.\n⭐ VIP: adding to queue and sharing on request.\nGuest: listens, votes, suggests tracks.\nMusic is synced for everyone; drift is corrected automatically.'}}
];
function buildGuideModal(){
const d=document.createElement('div');d.id='guide-modal';
d.innerHTML='<div class="guide-box"><button class="guide-close" onclick="closeGuide()">✕</button><h2 style="margin:0 0 14px;">📖 Справка MusicPulse</h2><div id="guide-content"></div></div>';
return d;
}
function openGuide(){
let m=document.getElementById('guide-modal');if(!m){m=buildGuideModal();document.body.appendChild(m);}
const c=document.getElementById('guide-content');c.innerHTML='';
const lang=(typeof currentLang!=='undefined'&&currentLang==='en')?'en':'ru';
GUIDE_SECTIONS.forEach(s=>{
const h=document.createElement('h3');h.className='guide-h';h.textContent=s.t[lang]||s.t.ru;c.appendChild(h);
if(s.img){const im=document.createElement('img');im.src=guideImgSrc(s.img);im.loading='lazy';im.onerror=function(){this.style.display='none';};c.appendChild(im);}
const p=document.createElement('p');p.className='guide-p';p.textContent=s.p[lang]||s.p.ru;c.appendChild(p);
});
m.classList.add('open');
}
function closeGuide(){const m=document.getElementById('guide-modal');if(m)m.classList.remove('open');}
document.addEventListener('DOMContentLoaded',()=>{
if(!document.getElementById('guide-fab')){
const b=document.createElement('button');b.id='guide-fab';b.className='guide-fab';b.textContent='❓';b.title='Справка / Guide';b.onclick=function(){const m=document.getElementById('guide-modal');if(m&&m.classList.contains('open'))closeGuide();else openGuide();};document.body.appendChild(b);
}
if(!document.getElementById('guide-modal'))document.body.appendChild(buildGuideModal());
const st=document.createElement('style');
st.textContent='.guide-fab{position:fixed;left:12px;bottom:12px;width:44px;height:44px;border-radius:50%;border:1px solid #3a3a3a;background:#1e1e1e;color:#b3b3b3;font-size:20px;cursor:pointer;z-index:3200;box-shadow:0 4px 12px rgba(0,0,0,.45);}.guide-fab:hover{color:#1db954;border-color:#1db954;}#guide-modal{position:fixed;inset:0;background:rgba(0,0,0,.78);display:none;align-items:center;justify-content:center;z-index:3100;}#guide-modal.open{display:flex;}#guide-modal .guide-box{width:720px;max-width:94vw;max-height:86vh;background:#1e1e1e;border:1px solid #3a3a3a;border-radius:14px;padding:22px;display:flex;flex-direction:column;position:relative;box-shadow:0 12px 40px rgba(0,0,0,.6);}#guide-content{overflow-y:auto;padding-right:8px;}.guide-close{position:absolute;top:12px;right:14px;background:none;border:none;color:#888;font-size:16px;cursor:pointer;padding:4px;line-height:1;z-index:2;}.guide-close:hover{color:#fff;}#guide-content .guide-h{font-size:14px;color:#1db954;margin:14px 0 6px;}#guide-content .guide-h:first-child{margin-top:0;}#guide-content .guide-p{font-size:13px;color:#ddd;line-height:1.55;margin:0 0 8px;white-space:pre-wrap;}#guide-content img{max-width:100%;border-radius:8px;border:1px solid #333;margin:4px 0 10px;display:block;}';
document.head.appendChild(st);
});