// ===== ОБЩИЕ ПОМОЩНИКИ =====
function escapeHtml(t){if(t===null||t===undefined)return'';return String(t).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#039;');}
function volumeToGain(v){return parseFloat(v)*2;}
function makeSoftClipCurve(){const s=512,c=new Float32Array(s);for(let i=0;i<s;i++){const x=(i/(s-1))*2-1;c[i]=Math.tanh(x*2);}return c;}
function formatFileSize(bytes){if(bytes<1024)return bytes+' B';if(bytes<1024*1024)return(bytes/1024).toFixed(1)+' KB';return(bytes/(1024*1024)).toFixed(2)+' MB';}
function formatTime(s){if(!s||isNaN(s))return'0:00';return Math.floor(s/60)+':'+String(Math.floor(s%60)).padStart(2,'0');}
function showToast(m,e){const el=document.getElementById('toast');if(!el)return;el.innerText=m;el.className=e?'toast show error':'toast show';setTimeout(function(){el.classList.remove('show');},2000);}
function showCustomModal(i,t,m,b){const o=document.getElementById('custom-modal');if(!o)return;document.getElementById('cm-icon').textContent=i;document.getElementById('cm-title').textContent=t;document.getElementById('cm-message').textContent=m;const c=document.getElementById('cm-buttons');c.innerHTML='';b.forEach(function(x){const btn=document.createElement('button');btn.className='cm-btn '+(x.class||'cancel');btn.textContent=x.text;btn.onclick=function(){o.classList.remove('open');if(x.action)x.action();};c.appendChild(btn);});o.classList.add('open');}
function showAlert(i,t,m){showCustomModal(i,t,m,[{text:translate('btn_ok'),class:'confirm-accent'}]);}
function showConfirm(i,t,m,f){showCustomModal(i,t,m,[{text:translate('btn_cancel'),class:'cancel'},{text:translate('btn_confirm'),class:'confirm-danger',action:f}]);}
function spinSetting(inputId,delta,minVal){minVal=minVal||0;const inp=document.getElementById(inputId);if(!inp)return;let v=parseInt(inp.value);if(isNaN(v))v=minVal;v+=delta;if(v<minVal)v=minVal;inp.value=v;inp.dispatchEvent(new Event('change'));}
class CustomAutocomplete{constructor(i,l,w,k){this.input=document.getElementById(i);this.list=document.getElementById(l);this.wrapper=document.getElementById(w);this.storageKey=k;this.items=[];this.selectedIndex=-1;this.maxHistory=20;this.isOpen=false;const self=this;this.input.addEventListener('input',function(){self.onInput();});this.input.addEventListener('keydown',function(e){self.onKeydown(e);});this.input.addEventListener('focus',function(){self.onInput();});document.addEventListener('click',function(e){if(!self.wrapper.contains(e.target))self.close();});}
getHistory(){try{return JSON.parse(localStorage.getItem(this.storageKey)||'[]');}catch(e){return[];}}
addToHistory(v){if(!v||!v.trim())return;let h=this.getHistory();h=h.filter(function(x){return x.toLowerCase()!==v.toLowerCase();});h.unshift(v.trim());if(h.length>this.maxHistory)h=h.slice(0,this.maxHistory);localStorage.setItem(this.storageKey,JSON.stringify(h));}
deleteFromHistory(v){let h=this.getHistory();h=h.filter(function(x){return x!==v;});localStorage.setItem(this.storageKey,JSON.stringify(h));this.onInput();}
onInput(){const v=this.input.value.toLowerCase().trim();let h=this.getHistory();if(v)h=h.filter(function(x){return x.toLowerCase().includes(v);});this.items=h;this.selectedIndex=-1;this.render(v);}
render(q){const self=this;if(!this.items.length){this.close();return;}this.list.innerHTML='';this.items.forEach(function(item){const d=document.createElement('div');d.className='ac-item';const s=document.createElement('span');s.style.cssText='flex:1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap';if(q){s.innerHTML=escapeHtml(item).replace(new RegExp('('+q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+')','gi'),function(m){return'<mark>'+m+'</mark>';});}else{s.textContent=item;}const db=document.createElement('span');db.className='ac-delete';db.textContent='✕';db.onclick=function(e){e.stopPropagation();self.deleteFromHistory(item);};d.appendChild(s);d.appendChild(db);d.onclick=function(){self.input.value=item;self.close();self.input.focus();};self.list.appendChild(d);});this.wrapper.classList.add('open');this.isOpen=true;}
close(){this.wrapper.classList.remove('open');this.selectedIndex=-1;this.isOpen=false;}
onKeydown(e){if(!this.isOpen)return;if(e.key==='ArrowDown'){e.preventDefault();this.selectedIndex=Math.min(this.selectedIndex+1,this.items.length-1);this.updateSelection();}else if(e.key==='ArrowUp'){e.preventDefault();this.selectedIndex=Math.max(this.selectedIndex-1,0);this.updateSelection();}else if(e.key==='Escape'){this.close();}}
updateSelection(){const self=this;const i=this.list.querySelectorAll('.ac-item');i.forEach(function(e,x){e.classList.toggle('selected',x===self.selectedIndex);if(x===self.selectedIndex)e.scrollIntoView({block:'nearest'});});}}